### ISSUE TITLE
Add `AirdropStart` option

### ISSUE THREAD

**Issue by lubtd** [ignite/modules#14]
Add `AirdropStart` as genesis state field or directly as a parameter (we need to determine if this value should be modifiable by governance by design)

Claims can only be performed once `AirdropStart` is reached.

This option would require discussion on the claim logic. Currently a mission is completed and claim is performed right after the action like staking, if the action is completed and `AirdropStart` is not yet reached then the claim would not be valid and the user must complete the action a second time after airdrop start.
If we want to require the user to only complete an action once to be able to claim the mission airdrop, we need to change the logic of `CompleteMission` so `CompleteMission` doesn't distribute the funds by registered the mission as completed but not claimed yet in the `ClaimRecord`. A message `MsgClaim` would allow to claim airdrop for completed but not claimed missions

**Comment by Pantani** [comment]
@lubtd, should we store the amount from being claimed calculated with the decay information from the moment the mission is completed, or should we calculate the value with the decay information when the user calls the `MsgClaim`?

We can also create an ante handler method to automatically distribute the fund when the `AirdropStart` reaches.  wdyt?

**Comment by Pantani** [comment]
> @lubtd, should we store the amount from being claimed calculated with the decay information from the moment the mission is completed, or should we calculate the value with the decay information when the user calls the `MsgClaim`?

IMHO re-calculate the decay information in `MsgClaim` will be better for the `AirdropSupply` and more simple

**Comment by lubtd** [comment]
> IMHO re-calculate the decay information in MsgClaim will be better for the AirdropSupply and more simple

Yes, I think this is the way to go. Just storing the mission ID that has been completed, and calculate dynamically.

In a hypothetical web UI to claim airdrop, clicking on "Stake" for example would send message to stake + claim message in the same transaction. In practice with the UI, the airdrop would be claimed directly so decay is not a concern

**Comment by lubtd** [comment]
>We can also create an ante handler method to automatically distribute the fund when the AirdropStart reaches. wdyt?

Would be end-block you rather mean?
I would avoid having extensive logic there. The user should go on a UI and it will appear if they can claim the airdrop

**Comment by Pantani** [comment]
> In a hypothetical web UI to claim airdrop, clicking on "Stake" for example would send message to stake + claim message in the same transaction. In practice with the UI, the airdrop would be claimed directly so decay is not a concern

We can also try to claim in the `CompleteMission` if the `AirdropStart` reached, but is not, the user can call the `MsgClaim`

**Comment by lubtd** [comment]
>We can also try to claim in the CompleteMission if the AirdropStart reached, but is not, the user can call the MsgClaim

Yes, it's actually a good idea and should not add complexity
