### ISSUE TITLE
Remove CLI dependency

### ISSUE THREAD

**Issue by tbruyelle** [ignite/modules#40]
This module depends on CLI because of `docs.Docs`. Since this repo is aimed to host things like `cosmoscmd`, it matters it doesn't depends on CLI.

Since this app structure is only here for testing purpose (as far as I understand), can we consider remove the doc part ?
The alternative is to copy the `cli/docs` folder into the repo, like for a scaffolded chain, but that represents more than 150 files.

Please tell me what is preferable.

**Comment by tbruyelle** [comment]
> but that represents more than 150 files

Seems like I mixed up `ignite/docs` and `chain/docs`, there's only a yaml file in the chain version. That said `ignite g openapi` returns an error when I try to run it inside this project, so I'm not sure how to generate this file.

**Comment by aljo242** [comment]
Yes, we can just go ahead and remove the docs part.  Thanks !
