### ISSUE TITLE
Can't send tx through `testappd` cli: account not found

### ISSUE THREAD

**Issue by lubtd** [ignite/modules#46]
**Describe the bug**
Seems the keys for test account in local testnet served by Ignite CLI are not available

I tested with an app scaffolded with Ignite CLI and the issue is not reproduced. Maybe related to some customization we add in the app?

**To Reproduce**
1. `ignite c serve -r`
2. `testappd tx claim claim-initial --from alice`
```
Error: alice.info: key not found
```

**Comment by tbruyelle** [comment]
I can reproduce. I ran a `find` on `alice.info` and it seems it's written in the wrong folder :

```
$HOME/.modules/keyring-test/alice.info
```

instead of

```
/home/tom/.testapp/keyring-test/alice.info
```

Seems like the app name used to generate the account is `modules` (the actual folder name) instead of `testapp`

**Comment by tbruyelle** [comment]
Adding the following to the `config.yml` file fixes the problem on my machine, but I don't think it's the best solution because of the hard path ^^

```yaml
init:
  home: /home/tom/.testapp
```

**Comment by lubtd** [comment]
Thanks for investigating this, so it was related to using a custom name for the app

It seems it works with
```
init:
  home: $HOME/.testapp
```

I think it's ok to assume `$HOME` is defined on the user machine?
