### ISSUE TITLE
Moving `errors` into `pkg/errors`

### ISSUE THREAD

**Issue by lubtd** [ignite/modules#47]
**Is your feature request related to a problem? Please describe.**

We put `errors` package at the root of the repository for simplicity.

However, with some recent discussion about eventually use the `errors` package in templates of scaffolded app, I think we should now move it into `pkg/errors` to be more future proof and avoid having errors in chain importing the `errors` package

`pkg` would represent in the future a list of utility packages that can be used to build Cosmos-SDK blockchain

**Comment by tbruyelle** [comment]
Do you mean a new `pkg` package in this repo, or the existing `ignite/cli/pkg` package ?

**Comment by lubtd** [comment]
> Personally as a user I don't expect to see utilities packages inside a repo called modules.

True but it's more like modules with a build-in environment for the development of those modules and to test them. Which includes reusable packages like `errors`, the primary usage of these packages are in the modules of the repo. `ignite/pkg` would be for more universal package, not for those where the primary usage would be for the modules.

**Comment by tbruyelle** [comment]
OK for errors indeed, but I had also in mind `cosmoscmd` and this one is not used in modules.
